/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface RoomInfo {
  'id' : string,
  'hostName' : string,
  'gridSize' : string,
  'playerCount' : bigint,
  'roomName' : string,
}
export interface _SERVICE {
  'createRoom' : ActorMethod<[string, string, string], string>,
  'getAndClearP2Inputs' : ActorMethod<[string], Array<string>>,
  'getAnswer' : ActorMethod<[string], [] | [string]>,
  'getGameState' : ActorMethod<[string], [] | [string]>,
  'getGuestIce' : ActorMethod<[string], Array<string>>,
  'getHighScore' : ActorMethod<[], bigint>,
  'getHostIce' : ActorMethod<[string], Array<string>>,
  'getOffer' : ActorMethod<[string], [] | [string]>,
  'isGameStarted' : ActorMethod<[string], boolean>,
  'joinRoom' : ActorMethod<[string], boolean>,
  'keepAlive' : ActorMethod<[string], undefined>,
  'leaveRoom' : ActorMethod<[string], undefined>,
  'listRooms' : ActorMethod<[], Array<RoomInfo>>,
  'pushAnswer' : ActorMethod<[string, string], undefined>,
  'pushGameState' : ActorMethod<[string, string], undefined>,
  'pushGuestIce' : ActorMethod<[string, string], undefined>,
  'pushHostIce' : ActorMethod<[string, string], undefined>,
  'pushOffer' : ActorMethod<[string, string], undefined>,
  'startGame' : ActorMethod<[string], undefined>,
  'submitP2Input' : ActorMethod<[string, string], undefined>,
  'submitScore' : ActorMethod<[bigint], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];