/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RoomInfo = IDL.Record({
  'id' : IDL.Text,
  'hostName' : IDL.Text,
  'gridSize' : IDL.Text,
  'playerCount' : IDL.Nat,
  'roomName' : IDL.Text,
  'gameStarted' : IDL.Bool,
});

export const idlService = IDL.Service({
  'createRoom' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'getAndClearP2Inputs' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], []),
  'getAnswer' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getGameState' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getGuestIce' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getHighScore' : IDL.Func([], [IDL.Nat], ['query']),
  'getHostIce' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getOffer' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'hasGuest' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isGameStarted' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'joinRoom' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'keepAlive' : IDL.Func([IDL.Text], [], []),
  'leaveRoom' : IDL.Func([IDL.Text], [], []),
  'leaveRoomAsGuest' : IDL.Func([IDL.Text], [], []),
  'leaveRoomAsHost' : IDL.Func([IDL.Text], [], []),
  'listRooms' : IDL.Func([], [IDL.Vec(RoomInfo)], ['query']),
  'pushAnswer' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'pushGameState' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'pushGuestIce' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'pushHostIce' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'pushOffer' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'startGame' : IDL.Func([IDL.Text], [], []),
  'submitP2Input' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitScore' : IDL.Func([IDL.Nat], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RoomInfo = IDL.Record({
    'id' : IDL.Text,
    'hostName' : IDL.Text,
    'gridSize' : IDL.Text,
    'playerCount' : IDL.Nat,
    'roomName' : IDL.Text,
    'gameStarted' : IDL.Bool,
  });
  
  return IDL.Service({
    'createRoom' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'getAndClearP2Inputs' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], []),
    'getAnswer' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getGameState' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getGuestIce' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getHighScore' : IDL.Func([], [IDL.Nat], ['query']),
    'getHostIce' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getOffer' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'hasGuest' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isGameStarted' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'joinRoom' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'keepAlive' : IDL.Func([IDL.Text], [], []),
    'leaveRoom' : IDL.Func([IDL.Text], [], []),
    'leaveRoomAsGuest' : IDL.Func([IDL.Text], [], []),
    'leaveRoomAsHost' : IDL.Func([IDL.Text], [], []),
    'listRooms' : IDL.Func([], [IDL.Vec(RoomInfo)], ['query']),
    'pushAnswer' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'pushGameState' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'pushGuestIce' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'pushHostIce' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'pushOffer' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'startGame' : IDL.Func([IDL.Text], [], []),
    'submitP2Input' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitScore' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };
